#pragma once
#include <string>
#include <string_view>

class Employee {
public:
	explicit Employee(std::string_view name);
	virtual ~Employee() = default; // Generated by the compiler
	
	void setName(std::string_view name);
	std::string getName() const;
	
	// Pure virtual functions makes the Employee class abstract
	virtual double earnings() const = 0; //pure virtual
	virtual std::string toString() const; //virtual 
private:
	std::string m_name;
};